# Generated by Django 4.2.7 on 2023-11-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_order_full_name_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='address_url',
            field=models.CharField(default=123, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pharmacy_buildings'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='opening_hours',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
